version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: local-nae3x-blog-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    restart: on-failure
